title: "She++"
description: "Brindar conocimientos para introducir al mundo tecnológico y empoderar a jóvenes mujeres en el mismo ámbito."
sitename: "She++"
baseurl: '/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
